### PR TITLE
creates hive-watcher/examples/out-as-csv/hive-watcher.py

### PR DESCRIPTION
**Pull request by seakintruth**
Alternatively it may be better to use stderr, instead of this new write_to_error_log() function in the stream loop error exception
```
import sys
...
        except: # catch *all* errors
            sys.stderr.write(sys.exc_info()[0])
```

### CODE REVIEW

**Comment by seakintruth** [comment]
If going to log to file, probably should use:
https://docs.python.org/3/howto/logging.html
```
import logging
logging.basicConfig(filename='example.log', encoding='utf-8', level=logging.DEBUG)
logging.debug('This message should go to the log file')
logging.info('So should this')
logging.warning('And this, too')
logging.error('And non-ASCII stuff, too, like Øresund and Malmö')
```

**Comment by daveajones** [comment]
@brianoflondon Ill let you review PR’s on the Python side.

**Comment by seakintruth** [comment]
Restored simple-watcher.py to original upstream file, and created example directory

**Comment by seakintruth** [comment]
pull request 29 replaces this pull request

**Pull request closed without merging**
